---
title: "Chapter 7: `forcats`"
execute:
  warning: false
format: 
  html:
    fig-height: 4
    embed-resources: true
---

```{r}
library(tidyverse)
library(here)
```

Class Exercise 1. Because defense is quantitative, plotting just the median removes the spread of the distribution, the shape of the distribution, etc. In general, bar plots and lollipop plots are used to show counts of a categorical variable or totals (not a quantitative variable).

Class Exercise 4.

```{r}
path <- "https://raw.githubusercontent.com/highamm/ds234_quarto/main/data_online/"
medals_df <- read_csv(paste0(path, "medals.csv"))
medals_df
```

Try steps 1 and 2:

```{r}
medals_type <- medals_df |> group_by(medal_type, country) |>
  summarise(n_medals = n())

medals_total <- medals_df |> group_by(country) |>
  summarise(n_total = n()) |>
  arrange(desc(n_total)) |>
  slice(1:20) 

## step 3
medals_joined <- semi_join(medals_type, medals_total,
                           join_by(country == country))
medals_joined

## step 4 and step 5
## geom_tile() with an x aes, y aes, and fill aes

## medal type should be gold, silver, bronze
## country should be ordered from most medals to least

medals_joined <- medals_joined |>
  ungroup() |>
  mutate(country_ord = fct_reorder(country, n_medals, .fun = sum)) |>
  mutate(medal_type = fct_relevel(medal_type,
                                  c("Gold Medal", "Silver Medal",
                                    "Bronze Medal")))

ggplot(data = medals_joined, aes(x = medal_type, y = country_ord,
                                 fill = n_medals)) +
  geom_tile() +
  scale_fill_viridis_c()
```